SPLIT_FILE=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass_multihead_crf/multilabel_maxTL256_batch16_chunk256_epochs30_paper --num_epochs=30 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DTAI-KULeuven/robbert-2023-dutch-base --multiclass --use_multihead_crf --split_file=$SPLIT_FILE;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass_multihead_crf/multilabel_maxTL256_batch16_chunk256_epochs30_paper --num_epochs=30 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=UMCU/CardioBERTa.nl_clinical --multiclass --use_multihead_crf --split_file=$SPLIT_FILE;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass_multihead_crf/multilabel_maxTL256_batch16_chunk256_epochs30_paper_paragraph --num_epochs=30 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=KB/bert-base-swedish-cased --multiclass --use_multihead_crf --split_file=$SPLIT_FILE;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass_multihead_crf/multilabel_maxTL256_batch16_chunk256_epochs30_paper_paragraph --num_epochs=30 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DT4H/CardioBERTa.sv --multiclass --use_multihead_crf --split_file=$SPLIT_FILE;
