# poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=20 --learning_rate=2e-5 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE MEDICATION --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_20epochs_classweights_3ldnn_2e5 --use_class_weights --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;

# poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=30 --learning_rate=2e-5 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE MEDICATION --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_30epochs_classweights_3ldnn_2e5 --use_class_weights --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;

# poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=20 --learning_rate=1e-5 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE MEDICATION --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_20epochs_classweights_3ldnn_1e5 --use_class_weights --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;

# poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=30 --learning_rate=1e-5 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE MEDICATION --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_30epochs_classweights_3ldnn_1e5 --use_class_weights --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;

poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=40 --learning_rate=5e-5 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_30epochs_3ldnn_5e5 --only_first_split --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;

poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=40 --learning_rate=2e-6 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_30epochs_3ldnn_2e5 --only_first_split --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;

poetry run python -m cardioner.main --lang=multi --corpus_train=../assets/CardioCCC/WithoutSuggestions/nl/cardioccc_nl.json  --parse_annotations --train_model --chunk_size=256 --max_token_length=256 --num_epochs=40 --learning_rate=1e-5 --weight_decay=1e-4 --batch_size=16 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --chunk_type=paragraph --entity_types DISEASE SYMPTOM PROCEDURE --classifier_hidden_layers 768 768 768 --output_dir=output/MedRoBERTa/CardioCCC_multilabel_batch16_256cl_30epochs_classweights_3ldnn_1e5 --only_first_split --split_file=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json;
