SPLIT_FILE=/media/bramiozo/Storage1/bramiozo/DEV/GIT/UMCU/CardioNER.nl/assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json

# poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/MedRoBERTa.nl/multilabel_maxTL256_batch16_chunk256_epochs20_paper --num_epochs=30 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --split_file=$SPLIT_FILE;

# poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/MedRoBERTa.nl/multiclass_maxTL256_batch16_chunk256_epochs20_paper_MEDICATION --num_epochs=20 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --multiclass --split_file=$SPLIT_FILE --entity_types MEDICATION;

# poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/MedRoBERTa.nl/multiclass_maxTL256_batch16_chunk256_epochs20_paper_PROCEDURE --num_epochs=20 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --multiclass --split_file=$SPLIT_FILE --entity_types PROCEDURE;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/MedRoBERTa.nl/multiclass_maxTL256_batch16_chunk256_epochs20_paper_paragraph_SYMPTOM --num_epochs=20 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --multiclass --split_file=$SPLIT_FILE --entity_types SYMPTOM;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/MedRoBERTa.nl/multiclass_maxTL256_batch16_chunk256_epochs20_paper_paragraph_DISEASE --num_epochs=20 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=CLTL/MedRoBERTa.nl --multiclass --split_file=$SPLIT_FILE --entity_types DISEASE;
