#poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --lang=sv --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --lang=sv --pipe=dt4h

poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --lang=sv --pipe=dt4h

poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --lang=sv --pipe=dt4h

poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --lang=sv --pipe=dt4h

#####################################################
#####################################################

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --lang=sv --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --lang=sv --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --lang=sv --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --lang=sv --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Swedish/cardioccc_sv.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --lang=sv --pipe=dt4h

# #####################################################
#####################################################

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERTa.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --lang=nl --pipe=dt4h

#####################################################
#####################################################

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multilabel/multilabel_maxTL256_batch16_chunk256_epochs10_paper_paragraph --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_MEDICATION --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --lang=nl --pipe=dt4h

# poetry run python -m cardioner.run_inference_on_folds --bulk_file=assets/CardioCCC/Dutch/cardioccc_nl.json --split_file=assets/CardioCCC/paper_splits/splits_cv10_holdout_test.json --model_folder=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --lang=nl --pipe=dt4h
