poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_DISEASE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DTAI-KULeuven/robbert-2023-dutch-base --force_splitter --num_splits=10 --entity_types DISEASE --multiclass;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_SYMPTOM --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DTAI-KULeuven/robbert-2023-dutch-base --force_splitter --num_splits=10 --entity_types SYMPTOM --multiclass;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_PROCEDURE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DTAI-KULeuven/robbert-2023-dutch-base --force_splitter --num_splits=10 --entity_types PROCEDURE --multiclass;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/RobBERT2023_base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_MEDICATION --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DTAI-KULeuven/robbert-2023-dutch-base --force_splitter --num_splits=10 --entity_types MEDICATION --multiclass;





poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERT.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_DISEASE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=UMCU/CardioBERTa.nl_clinical --force_splitter --num_splits=10 --entity_types DISEASE --multiclass;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERT.nl/multiclass/multilabel_maxTL256_batch16_chunk256_epochs10_paper_SYMPTOM --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=UMCU/CardioBERTa.nl_clinical --force_splitter --num_splits=10 --entity_types SYMPTOM --multiclass;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERT.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_PROCEDURE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=UMCU/CardioBERTa.nl_clinical --force_splitter --num_splits=10 --entity_types PROCEDURE --multiclass;

poetry run python -m cardioner.main --lang=nl --corpus_train assets/CardioCCC/Dutch/cardioccc_nl.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/NL/CardioBERT.nl/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_MEDICATION --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=UMCU/CardioBERTa.nl_clinical --force_splitter --num_splits=10 --entity_types MEDICATION --multiclass;







poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=KB/bert-base-swedish-cased --force_splitter --num_splits=10 --entity_types DISEASE --multiclass;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=KB/bert-base-swedish-cased --force_splitter --num_splits=10 --entity_types SYMPTOM --multiclass;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclassl_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=KB/bert-base-swedish-cased --force_splitter --num_splits=10 --entity_types PROCEDURE --multiclass;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/SV-BERT-base/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_MEDICATION --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=KB/bert-base-swedish-cased --force_splitter --num_splits=10 --entity_types MEDICATION --multiclass;



poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_DISEASE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DT4H/CardioBERTa.sv --force_splitter --num_splits=10 --entity_types DISEASE --multiclass;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_SYMPTOM --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DT4H/CardioBERTa.sv --force_splitter --num_splits=10 --entity_types SYMPTOM --multiclass;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_paragraph_PROCEDURE --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DT4H/CardioBERTa.sv --force_splitter --num_splits=10 --entity_types PROCEDURE --multiclass;

poetry run python -m cardioner.main --lang=sv --corpus_train assets/CardioCCC/Swedish/cardioccc_sv.json --parse_annotations --train_model --max_token_length 256 --chunk_size 256 --batch_size 16 --chunk_type=paragraph --output_dir=/media/bramiozo/Storage2/DATA/NER/DT4H_results/paper/SV/CardioBERTa.sv/multiclass/multiclass_maxTL256_batch16_chunk256_epochs10_paper_MEDICATION --num_epochs=10 --learning_rate=2e-5 --weight_decay=1e-4 --accumulation_steps=1 --model=DT4H/CardioBERTa.sv --force_splitter --num_splits=10 --entity_types MEDICATION --multiclass;
